// Tajseer Learning World — Bilingual content
// All content source-supported from TAJSEER-MASTER-CONTEXT.md and raw source files.
// Authentic Tajseer copy — no corrupted characters or placeholders.

export const copy = {
  en: {
    skip: "Skip to main content",
    motion: "Reduce motion",
    reading: "Reading view",
    world: "Spatial view",
    language: "العربية",
    hero: {
      tagline: "TAJSEER · SAUDI ARABIA · SINCE 2009",
      heading: ["Educational content.", "Interactive experiences."],
      body: "Tajseer is a company specialized in e-learning course development, distance learning and training, virtual reality, STEM methodology, and educational consultancy. Since its inception in the Kingdom of Saudi Arabia in 2009, the company plans, implements, develops and programmes e-learning and distance learning projects.",
      cta: "Begin the journey",
      scroll: "SCROLL TO DISCOVER",
      serviceIndex: "FIVE CAPABILITIES. ONE LEARNING EXPERIENCE.",
    },
    services: [
      { id: "multimedia", name: "Interactive Multimedia", short: "Multimedia" },
      { id: "courses", name: "E-learning Course Development", short: "E-learning" },
      { id: "stem", name: "STEM Methodology", short: "STEM" },
      { id: "arvr", name: "AR and VR Environments", short: "AR / VR" },
      { id: "guidance", name: "Training and Consulting", short: "Consulting" },
    ],
    multimedia: {
      eyebrow: "01 / INTERACTIVE MULTIMEDIA",
      heading: ["Content that", "speaks."],
      body: "At Tajseer, designers develop professional graphic interfaces with close attention to detail and to the selection, contrast and meaning of colors. Tajseer produces designs, graphics, user interfaces and interactive activities, as well as professional clips that include video and audio recordings, animation and motion graphics.",
      caption: "Content becomes expressive.",
      note: "Illustrative demonstration — not a delivered client project.",
    },
    courses: {
      eyebrow: "02 / E-LEARNING COURSE DEVELOPMENT",
      heading: ["Learning becomes", "organized."],
      body: "Tajseer is committed to developing reliable and purposeful digital educational materials that comply with global e-learning standards. The courses are designed for computers, smart devices and various operating systems (iOS/Android), with a friendly interface and content matched to individual learner needs. The service includes SCORM compatibility and technical support for publishing on LMS/CMS/MOOCs.",
      note: "Course sequence shown is illustrative.",
    },
    stem: {
      eyebrow: "03 / STEM METHODOLOGY",
      heading: ["One idea,", "explored."],
      body: "Tajseer provides services for creating courses and educational packages based on the STEM methodology, implementing specialized training workshops and educational/instructional design models.",
      inspect: "Inspect a component",
      stopInspect: "Finish inspecting",
      drag: "Drag the model to inspect · Escape to finish",
      braced: "Triangulated",
      unbraced: "Unbraced",
      compare: "01 / COMPARE CONFIGURATIONS",
      manipulate: "02 / EXPLORE THE MODEL",
      explode: "Separate the parts",
      dimensions: "Show dimensions",
      reassemble: "Reassemble",
      reset: "Reset experiment",
      shear: "Move the upper joints",
      rotateLeft: "Rotate left",
      rotateRight: "Rotate right",
      view: "Reset view",
      bracedNote: "The diagonal holds the relationship between the corners. This illustrative frame stays in shape.",
      unbracedNote: "Without a diagonal, the corners can change angle. Move the slider to explore that freedom.",
      conceptual: "A conceptual learning experience — not a structural simulation.",
      units: "Lengths use diagram units, not engineering specifications.",
      select: "Inspect a component",
      none: "Choose a joint or member",
      selectionLabel: "COMPONENT STUDY",
      jointNote: "A joint connects members. Its neighbors show how a local connection belongs to the whole structure.",
      braceNote: "This diagonal divides a four-sided frame into triangles. It constrains how the corners can move relative to each other.",
      memberNote: "A member connects two joints. Follow its highlighted neighbors to understand the connections around it.",
      ready: "Select a component or change the frame.",
    },
    arvr: {
      eyebrow: "04 / AR AND VR ENVIRONMENTS",
      heading: ["Inside", "knowledge."],
      body: "Tajseer keeps pace with rapid developments in virtual education technologies, providing services for designing and developing virtual laboratories for technical and vocational education using 360 image, augmented reality (AR) and virtual reality (VR) technologies. We also develop 2D/3D educational games and employ VR technologies and holograms in composing lessons based on the STEM methodology.",
      peak: "The visitor is now inside educational content.",
      note: "Capability illustration — does not prove deployed hardware or specific installations.",
    },
    guidance: {
      eyebrow: "05 / TRAINING AND CONSULTING",
      heading: ["Complexity becomes", "direction."],
      body: "Tajseer provides educational consultancy and develops training packages to support clients in acquiring skills and knowledge through interaction with specialized consultant expertise. Tajseer attributes its professional experience to its consultants' exposure to local and international institutions and organizations and to the application of best practices in training and consulting.",
      note: "Guidance pathway shown is illustrative.",
    },
    mission: {
      eyebrow: "06 / MISSION AND VISION",
      missionLabel: "Mission",
      missionText: "We strive to provide an interactive learning environment for the largest segment of society by using the latest software technologies to break the barrier and routine of classrooms by meeting the future aspirations for education.",
      visionLabel: "Vision",
      visionText: "Play a unique role in enhancing the educational and academic level in educational institutions to keep pace with the vast variety in educational process.",
    },
    company: {
      eyebrow: "07 / TAJSEER",
      about: "About",
      profileHeading: "Tajseer",
      profile: "Tajseer is a company specialized in the development of e-learning courses, distance learning and training, virtual reality, STEM methodology, and training and educational consultancy based on the needs of real and virtual e-learning solutions. Since its inception in the Kingdom of Saudi Arabia in 2009, the company has planned, implemented, developed and programmed e-learning and distance-learning projects, following best practices and educational technologies to raise the educational and academic level of its target groups.",
      contactHeading: "Contact",
      address: "Riyadh — Olaya Street",
      email: "private@tajseerksa.com",
      phones: ["00966-114-621-717", "00966-545-992-326"],
      closing: "Thinking × Technology × Education",
      closingAr: "التفكير × التقنية × التعليم",
    },
    fallback: "Tajseer — Educational Technology Services",
    fallbackNote: "The same Tajseer service information is available without 3D.",
  },

  ar: {
    skip: "تخطّ إلى المحتوى الرئيسي",
    motion: "تقليل الحركة",
    reading: "عرض القراءة",
    world: "العرض المكاني",
    language: "EN",
    hero: {
      tagline: "تجسير الفكر · المملكة العربية السعودية · منذ ٢٠٠٩",
      heading: ["محتوى تعليمي.", "تجارب تفاعلية."],
      body: "تجسير الفكر شركة متخصصة في مجال تطوير المقررات الإلكترونية والتعلم والتدريب عن بعد والواقع الافتراضي ومنهجية ستيم والاستشارات التعليمية والتربوية. حرصت الشركة منذ نشأتها في المملكة العربية السعودية عام ٢٠٠٩، على التخطيط والتنفيذ والتطوير والبرمجة لمشاريع التعليم الإلكتروني والتعلم عن بعد.",
      cta: "ابدأ الرحلة",
      scroll: "مرّر لتكتشف",
      serviceIndex: "خمس قدرات. تجربة تعلّم واحدة.",
    },
    services: [
      { id: "multimedia", name: "وسائط متعددة تفاعلية", short: "الوسائط" },
      { id: "courses", name: "تطوير المقررات الإلكترونية", short: "المقررات" },
      { id: "stem", name: "منهجية STEM", short: "STEM" },
      { id: "arvr", name: "بيئات الواقع المعزز والافتراضي", short: "AR / VR" },
      { id: "guidance", name: "التدريب والاستشارات", short: "الاستشارات" },
    ],
    multimedia: {
      eyebrow: "٠١ / وسائط متعددة تفاعلية",
      heading: ["محتوى", "يتكلّم."],
      body: "يتمتع المصممون في تجسير بخيال واسع لتطوير واجهات رسوم احترافية مع الاهتمام بالتفاصيل وانتقاء الألوان وتباينها ودلالاتها، وذلك لإنتاج التصاميم والرسوم وواجهات المستخدم والأنشطة التفاعلية. كما يتم إنتاج مقاطع احترافية تشمل تسجيلات الفيديو والمقاطع الصوتية، بالإضافة إلى تطوير الرسوم المتحركة والصور المتحركة (Motion Graphics).",
      caption: "يصبح المحتوى معبّراً.",
      note: "عرض توضيحي — ليس مشروعاً فعلياً لأحد العملاء.",
    },
    courses: {
      eyebrow: "٠٢ / تطوير المقررات الإلكترونية",
      heading: ["التعلّم يصبح", "منظّماً."],
      body: "تلتزم تجسير بتطوير مواد تعليمية رقمية موثوقة وهادفة تتوافق مع المعايير العالمية للتعليم الإلكتروني. وتتميز المقررات التي يتم تطويرها بتوافقها مع أجهزة الحاسب والأجهزة الذكية ونظم التشغيل المختلفة (iOS/Android)، كما تتضمن رحلة مستخدم تتوافق مع الاحتياجات الفردية لكل متعلم، مع ضمان توافقية المحتوى الرقمي مع معايير SCORM وتقديم الدعم الفني للنشر على LMS/CMS/MOOCs.",
      note: "تسلسل المقررات المعروض توضيحي.",
    },
    stem: {
      eyebrow: "٠٣ / منهجية STEM",
      heading: ["فكرة واحدة،", "تستكشف."],
      body: "تقدم تجسير خدمات تأليف المقررات والحقائب التعليمية المبنية على منهجية STEM، بالإضافة إلى تنفيذ ورش تدريبية متخصصة بكل مجالاتها، وإعداد نماذج التصميم التعليمي التي تتمثل في تحويل المحتوى النصي إلى نموذج رقمي تفاعلي.",
      inspect: "افحص أحد المكونات",
      stopInspect: "إنهاء الفحص",
      drag: "اسحب النموذج لفحصه · اضغط Escape للإنهاء",
      braced: "مع دعامة قطرية",
      unbraced: "دون دعامة",
      compare: "٠١ / قارن التكوينين",
      manipulate: "٠٢ / استكشف النموذج",
      explode: "فصل الأجزاء",
      dimensions: "إظهار الأبعاد",
      reassemble: "إعادة التجميع",
      reset: "إعادة ضبط التجربة",
      shear: "حرّك المفاصل العلوية",
      rotateLeft: "تدوير لليسار",
      rotateRight: "تدوير لليمين",
      view: "إعادة المنظر",
      bracedNote: "يحافظ القطر على العلاقة بين الزوايا. يبقى هذا الإطار التوضيحي محافظاً على شكله.",
      unbracedNote: "دون قطر، يمكن للزوايا أن تتغيّر. حرّك المؤشر لاستكشاف هذه الحرية.",
      conceptual: "تجربة تعليمية مفاهيمية، وليست محاكاة إنشائية.",
      units: "الأطوال بوحدات تخطيطية، وليست مواصفات هندسية.",
      select: "افحص أحد المكونات",
      none: "اختر مفصلاً أو عنصراً",
      selectionLabel: "دراسة المكوّن",
      jointNote: "يربط المفصل بين العناصر. تكشف العناصر المجاورة كيف تنتمي هذه الوصلة إلى الهيكل بأكمله.",
      braceNote: "يقسم هذا القطر الإطار الرباعي إلى مثلثات، ويقيّد حركة الزوايا بالنسبة إلى بعضها.",
      memberNote: "يربط العنصر بين مفصلين. تتبّع العناصر المجاورة المضيئة لفهم العلاقات المحيطة به.",
      ready: "اختر مكوّناً أو غيّر الإطار.",
    },
    arvr: {
      eyebrow: "٠٤ / بيئات الواقع المعزز والافتراضي",
      heading: ["داخل", "المعرفة."],
      body: "تواكب تجسير التطورات المتسارعة في تقنيات التعليم والتدريب الواقعي والافتراضي، حيث تقدم خدمات تصميم وتطوير مختبرات افتراضية للتعلم المهني من خلال استخدام تقنيات الصورة 360 والواقع المعزز والواقع الافتراضي. كما تعمل على تطوير الألعاب التعليمية وتوظيف تقنيات VR والهولوجرام في تأليف دروس مبنية على منهجية STEM.",
      peak: "المتصفّح الآن داخل المحتوى التعليمي.",
      note: "توضيح للقدرات — لا يثبت تثبيتات فعلية محددة.",
    },
    guidance: {
      eyebrow: "٠٥ / التدريب والاستشارات",
      heading: ["التعقيد يصبح", "اتجاهًا."],
      body: "تقدم تجسير خدمات في مجالات الاستشارات التعليمية وتطوير الحقائب التدريبية بما يدعم اكتساب العملاء مهارات ومعرفة جديدة من خلال التفاعل مع خبرات الاستشاريين المتخصصة. وتكتسب تجسير خبرتها المهنية نتيجة لتعرض مستشاريها لخبرات مع مؤسسات وهيئات محلية وعالمية وتطبيق أفضل الممارسات في مجالات التدريب والاستشارات.",
      note: "مسار الإرشاد المعروض توضيحي.",
    },
    mission: {
      eyebrow: "٠٦ / الرسالة والرؤية",
      missionLabel: "الرسالة",
      missionText: "نسعى جاهدين لتوفير بيئة تعلم تفاعلية لأكبر شريحة من المجتمع باستخدام أحدث التقنيات البرمجية لكسر حاجز وروتين القاعات الدراسية وذلك بتلبية الطموحات والتطلعات المستقبلية للتعليم.",
      visionLabel: "الرؤية",
      visionText: "المساهمة في تعزيز المستوى التعليمي والأكاديمي في المؤسسات التعليمية لمواكبة العصر وتطوير العملية التعليمية.",
    },
    company: {
      eyebrow: "٠٧ / تجسير",
      about: "من نحن",
      profileHeading: "تجسير الفكر",
      profile: "تجسير الفكر شركة متخصصة في مجال تطوير المقررات الإلكترونية والتعلم والتدريب عن بعد والواقع الافتراضي ومنهجية ستيم والاستشارات التعليمية والتربوية، وتعمل على تلبية احتياجات حلول التعليم الإلكتروني الواقعي والافتراضي. حرصت الشركة منذ نشأتها في المملكة العربية السعودية عام ٢٠٠٩، على التخطيط والتنفيذ والتطوير والبرمجة لمشاريع التعليم الإلكتروني والتعلم عن بعد، وذلك باتباع أفضل الممارسات وأحدث التقنيات التعليمية ضمن أعلى الأسس والمعايير الدولية، للارتقاء بالمستوى التعليمي والأكاديمي للفئات المستهدفة.",
      contactHeading: "التواصل",
      address: "الرياض - شارع العليا",
      email: "private@tajseerksa.com",
      phones: ["00966-114-621-717", "00966-545-992-326"],
      closing: "Thinking × Technology × Education",
      closingAr: "التفكير × التقنية × التعليم",
    },
    fallback: "تجسير — خدمات التقنية التعليمية",
    fallbackNote: "معلومات خدمات تجسير متاحة دون العرض ثلاثي الأبعاد.",
  },
};

export type CopyLang = typeof copy.en;
